import { IDealer } from './IDealer.interface';
import { IDealerProduct } from './IDealerProduct.interface';
import { IProduct } from './IProduct.interface';

export const API_URL = 'http://localhost:8001/api/v1';

export const INITIAL_MARKETING_DEALER: IDealer[] = [
  {
    id: 0,
    name: 'Список диллеров не загружен'
  }
];

export const INITIAL_MARKETING_DEALERPRICE: IDealerProduct[] = [
  {
    id: 0,
    product_key: '',
    price: 0,
    product_url: '',
    product_name: '',
    date: '',
    dealer_id: 0,
    mapped: null
  }
];

export const INIRIAL_MARKETING_PRODUCTS: IProduct[] = [
  {
    FIELD1: 0,
    id: 0,
    article: '',
    ean_13: 0,
    name: '',
    cost: 0,
    recommended_price: 0,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  }
];

export const TEST_MARKETING_DEALER: IDealer[] = [
  {
    id: 1,
    name: 'Moi_vibor_WB'
  },
  {
    id: 2,
    name: 'Akson'
  },
  {
    id: 3,
    name: 'Bafus'
  },
  {
    id: 5,
    name: 'Castorama'
  },
  {
    id: 6,
    name: 'Cubatora'
  },
  {
    id: 7,
    name: 'Komus'
  },
  {
    id: 9,
    name: 'Megastroy'
  },
  {
    id: 10,
    name: 'OnlineTrade'
  },
  {
    id: 11,
    name: 'Petrovich'
  },
  {
    id: 12,
    name: 'sdvor'
  },
  {
    id: 13,
    name: 'simaLand'
  },
  {
    id: 14,
    name: 'VegosM'
  },
  {
    id: 15,
    name: 'Vse_instrumeni'
  },
  {
    id: 16,
    name: 'Vimos'
  },
  {
    id: 4,
    name: 'Baucenter'
  },
  {
    id: 8,
    name: 'Leroy_Merlin'
  },
  {
    id: 18,
    name: 'Мasterstroy_spb_OZON\n'
  },
  {
    id: 17,
    name: 'Unicleaner_OZON'
  }
];

export const TEST_MARKETING_DEALERPRICE: IDealerProduct[] = [
  {
    id: 2,
    product_key: '546227',
    price: 233,
    product_url: 'https://akson.ru//p/sredstvo_universalnoe_prosept_universal_spray_500ml/',
    product_name: 'Средство универсальное Prosept Universal Spray, 500мл',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 3,
    product_key: '546408',
    price: 175,
    product_url: 'https://akson.ru//p/kontsentrat_prosept_multipower_dlya_mytya_polov_tsitrus_1l/',
    product_name: 'Концентрат Prosept Multipower для мытья полов, цитрус 1л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 4,
    product_key: '546234',
    price: 285,
    product_url:
      'https://akson.ru//p/sredstvo_dlya_chistki_lyustr_prosept_universal_anti_dust_500ml/',
    product_name: 'Средство для чистки люстр Prosept Universal Anti-dust, 500мл',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 5,
    product_key: '651258',
    price: 362,
    product_url: 'https://akson.ru//p/udalitel_rzhavchiny_prosept_rust_remover_0_5l_023_05/',
    product_name: 'Удалитель ржавчины PROSEPT RUST REMOVER 0,5л 023-05',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 6,
    product_key: '546355',
    price: 205,
    product_url:
      'https://akson.ru//p/sredstvo_moyushchee_dlya_bani_i_sauny_prosept_multipower_wood_1l/',
    product_name: 'Средство моющее для бани и сауны Prosept Multipower Wood 1л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 7,
    product_key: '831859',
    price: 370,
    product_url: 'https://akson.ru//p/propitka_prosept_aquaisol_dlya_kamnya_kontsentrat_1_2_1l/',
    product_name: 'Пропитка PROSEPT Aquaisol для камня, концентрат  1:2  1л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 8,
    product_key: '546406',
    price: 235,
    product_url:
      'https://akson.ru//p/sredstvo_dlya_mytya_plitki_i_keramogranita_prosept_multipower_kerama_1l/',
    product_name: 'Средство для мытья плитки и керамогранита Prosept Multipower Kerama 1л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 9,
    product_key: '831858',
    price: 1648,
    product_url: 'https://akson.ru//p/propitka_prosept_aquaisol_dlya_kamnya_kontsentrat_1_2_5l/',
    product_name: 'Пропитка PROSEPT Aquaisol для камня, концентрат  1:2   5л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 10,
    product_key: '857015',
    price: 371,
    product_url:
      'https://akson.ru//p/shpatlevka_zamazka_proseptn_plastix_dlya_zadelki_glubokih_vyboin_i_treschin_1_4kg/',
    product_name: 'Шпаклевка выравнивающая акриловая PROSEPT Plastix белая, 1 кг.',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 11,
    product_key: '651265',
    price: 235,
    product_url: 'https://akson.ru//p/sol_dlya_posudomoechnykh_mashin_prosept_splash_1_5kg_280_15/',
    product_name: 'Соль для посудомоечных машин PROSEPT Splash 1,5кг 280-15',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 12,
    product_key: '546257',
    price: 182,
    product_url:
      'https://akson.ru//p/sredstvo_dlya_mytya_stekol_i_zerkal_prosept_optic_crystal_500ml/',
    product_name: 'Средство для мытья стекол и зеркал Prosept Optic Crystal, 500мл',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 13,
    product_key: '831854',
    price: 566,
    product_url:
      'https://akson.ru//p/antiseptik_prosept_eco_ultra_nevymyvaemyy_korichnevyy_gotovyy_sostav_5l/',
    product_name: 'Антисептик PROSEPT Eco Ultra невымываемый, коричневый, готовый состав 5л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 14,
    product_key: '831857',
    price: 559,
    product_url: 'https://akson.ru//p/ochistitel_fasadov_prosept_salt_cleaner_kontsentrat_1_2_1l/',
    product_name: 'Очиститель фасадов  PROSEPT Salt Cleaner, концентрат 1:2  1л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 15,
    product_key: '382757',
    price: 1037,
    product_url:
      'https://akson.ru//p/antiseptik_prosept_eco_ultra_nevymyvaemyy_dlya_otvetstvennyh_konstruktsiy_10l/',
    product_name:
      'Пропитка-антисептик PROSEPT Eco Ultra невымываемая для ответственных конструкций 10л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 16,
    product_key: '546322',
    price: 245,
    product_url:
      'https://akson.ru//p/sredstvo_kontsentrirovannoe_prosept_duty_extra_dlya_uborki_posle_stroitelstva_1l/',
    product_name: 'Средство концентрированное Prosept Duty Extra для уборки после строительства 1л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 17,
    product_key: '831860',
    price: 2496,
    product_url: 'https://akson.ru//p/udalitel_tsementa_prosept_cement_cleaner_kontsentrat_1_2_5l/',
    product_name: 'Удалитель цемента  PROSEPT Cement Cleaner, концентрат 1:2  5л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 18,
    product_key: '832157',
    price: 3762,
    product_url:
      'https://akson.ru//p/antiseptik_prosept_ultra_nevymyvaemyy_korichnevyy_kontsentrat_1_10_5l/',
    product_name: 'Антисептик PROSEPT Ultra невымываемый , коричневый концентрат 1:10  5л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 19,
    product_key: '382745',
    price: 1771,
    product_url:
      'https://akson.ru//p/ognebiozaschita_prosept_prof_1_gruppa_dlya_naruzhnyh_i_vnutrennih_rabot_10l/',
    product_name: 'Огнебиозащита PROSEPT prof 1 группа для наружных и внутренних работ 10л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 20,
    product_key: '831863',
    price: 460,
    product_url:
      'https://akson.ru//p/antiseptik_prosept_interior_dlya_vnutrennih_rabot_kontsentrat_1_10_1l/',
    product_name: 'Антисептик PROSEPT Interior для внутренних работ, концентрат 1:10  1л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 21,
    product_key: '856331',
    price: 349,
    product_url: 'https://akson.ru//p/shpatlevka_dlya_plit_osb_proplast_1_3_kg/',
    product_name: 'Шпаклевка для OSB-плит акриловая PROSEPT Proplast белая, 1 кг.',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 22,
    product_key: '695083',
    price: 243,
    product_url: 'https://akson.ru//p/antiseptik_grunt_prosept_osb_base_dlya_osb_1l/',
    product_name: 'Антисептик-грунт PROSEPT ОSB BASE для OSB 1л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 23,
    product_key: '831856',
    price: 2504,
    product_url: 'https://akson.ru//p/ochistitel_fasadov_prosept_salt_cleaner_kontsentrat_1_2_5l/',
    product_name: 'Очиститель фасадов  PROSEPT Salt Cleaner, концентрат 1:2  5л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 24,
    product_key: '546294',
    price: 253,
    product_url:
      'https://akson.ru//p/sredstvo_dlya_izdeliy_iz_kozhi_prosept_duty_leather_ochistka_i_ukhod_400ml/',
    product_name: 'Средство для изделий из кожи Prosept Duty Leather очистка и уход, 400мл',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 25,
    product_key: '546360',
    price: 229,
    product_url:
      'https://akson.ru//p/cprey_dlya_ochistki_polkov_v_banyakh_i_saunakh_prosept_universal_wood_500ml/',
    product_name: 'Cпрей для очистки полков в банях и саунах Prosept Universal Wood 500мл',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 26,
    product_key: '832158',
    price: 1783,
    product_url:
      'https://akson.ru//p/antiseptik_prosept_interior_dlya_vnutrennih_rabot_kontsentrat_1_10_5l/',
    product_name: 'Антисептик PROSEPT Interior для внутренних работ , концентрат 1:10 5л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 27,
    product_key: '831853',
    price: 1037,
    product_url:
      'https://akson.ru//p/antiseptik_prosept_eco_ultra_nevymyvaemyy_korichnevyy_gotovyy_sostav_10l/',
    product_name: 'Антисептик PROSEPT Eco Ultra невымываемый, коричневый, готовый состав 10л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 28,
    product_key: '832159',
    price: 546,
    product_url:
      'https://akson.ru//p/antiseptik_prosept_eco_interior_dlya_vnutrennih_rabot_gotovyy_sostav_5l/',
    product_name: 'Антисептик PROSEPT Eco Interior для внутренних работ, готовый состав  5л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 29,
    product_key: '546405',
    price: 382,
    product_url:
      'https://akson.ru//p/maslo_dlya_zashchity_polkov_prosept_sauna_oil_250ml_gotovyy_sostav/',
    product_name: 'Масло для защиты полков Prosept Sauna Oil, 250мл  готовый состав',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 30,
    product_key: '831855',
    price: 784,
    product_url:
      'https://akson.ru//p/antiseptik_prosept_ultra_nevymyvaemyy_korichnevyy_gotovyy_sostav_1_l/',
    product_name: 'Антисептик PROSEPT Ultra невымываемый, коричневый, готовый состав 1 л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 31,
    product_key: '856995',
    price: 1798,
    product_url: 'https://akson.ru//p/shpatlevka_dlya_plit_osb_proplast_7_0_kg/',
    product_name: 'Шпаклевка для OSB-плит акриловая PROSEPT Proplast белая, 7 кг.',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 32,
    product_key: '382756',
    price: 559,
    product_url:
      'https://akson.ru//p/antiseptik_prosept_eco_exterior_trudnovymyvaemyy_dlya_naruzhnyh_rabot_5l/',
    product_name: 'Пропитка-антисептик PROSEPT Eco Exterior трудновымываемая для наружных работ 5л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 33,
    product_key: '856325',
    price: 308,
    product_url:
      'https://akson.ru//p/otbelivatel_dlya_drevesiny_prosept_eco_50_gotovyy_sostav_1_kg/',
    product_name: 'Отбеливатель для древесины PROSEPT ECO 50 готовый  состав / 1 кг',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 1561,
    product_key: '44231946',
    price: 994,
    product_url: 'https://www.wildberries.ru/catalog/44231946',
    product_name: 'ОSB BASE',
    date: '2023-07-11',
    dealer_id: 1,
    mapped: null
  },
  {
    id: 34,
    product_key: '695084',
    price: 814,
    product_url: 'https://akson.ru//p/antiseptik_grunt_prosept_osb_base_dlya_osb_5l/',
    product_name: 'Антисептик-грунт PROSEPT ОSB BASE для OSB 5л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 35,
    product_key: '856324',
    price: 992,
    product_url:
      'https://akson.ru//p/ochistitel_epoksidnogo_naleta_prosept_epoxy_cleaner_gotovyy_sostav_0_5_l/',
    product_name: 'Очиститель эпоксидного налета PROSEPT EPOXY CLEANER, готовый состав / 0,5 л',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 36,
    product_key: '546253',
    price: 334,
    product_url:
      'https://akson.ru//p/sredstvo_dlya_chistki_grilya_i_dukhovykh_shkafov_prosept_cooky_grill_550ml_kontsentrat/',
    product_name:
      'Средство для чистки гриля и духовых шкафов Prosept Cooky Grill, 550мл концентрат',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 37,
    product_key: '546242',
    price: 210,
    product_url:
      'https://akson.ru//p/sprey_prosept_cooky_spray_dlya_stoleshnits_i_rakovin_iz_iskusstvennogo_kamnya_i_granita_500ml/',
    product_name:
      'Спрей Prosept Cooky Spray для столешниц и раковин из искусственного камня и гранита, 500мл',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  },
  {
    id: 38,
    product_key: '546258',
    price: 204,
    product_url:
      'https://akson.ru//p/credstvo_dlya_mytya_stekol_i_zerkal_s_antistaticheskim_effektom_prosept_optic_shine_500ml/',
    product_name:
      'Cредство для мытья стекол и зеркал с антистатическим эффектом Prosept Optic Shine, 500мл',
    date: '2023-07-11',
    dealer_id: 2,
    mapped: null
  }
];

export const TEST_MARKETING_PRODUCTS: IProduct[] = [
  {
    FIELD1: 0,
    id: 245,
    article: '008-1',
    ean_13: 4680008140234,
    name: 'Антисептик невымываемыйPROSEPT ULTRAконцентрат 1:10  / 1 л',
    cost: 360,
    recommended_price: 858,
    category_id: 20,
    ozon_name:
      'Антисептик невымываемый для ответственных конструкций PROSEPT ULTRA, концентрат, 1 л.',
    name_1c:
      'Антисептик невымываемый для ответственных конструкций PROSEPT ULTRA, концентрат, 1 л.',
    wb_name:
      'Антисептик невымываемый для ответственных конструкций PROSEPT ULTRA, концентрат, 1 л.',
    ozon_article: 189522705,
    wb_article: 150033482,
    ym_article: '008-1',
    wb_article_td: ''
  },
  {
    FIELD1: 1,
    id: 3,
    article: '242-12',
    ean_13: null,
    name: 'Антигололед - 32 PROSEPTготовый состав / 12 кг',
    cost: 460.16,
    recommended_price: 1075,
    category_id: null,
    ozon_name: '',
    name_1c: 'Антигололед - 32 PROSEPTготовый состав / 12 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 2,
    id: 443,
    article: '0024-06 с',
    ean_13: 4680008145208,
    name: 'Герметик акриловый цвет сосна, ф/п 600мл',
    cost: 307,
    recommended_price: 644,
    category_id: 25,
    ozon_name:
      'Герметик акриловый для швов для деревянных домов, конструкций, изделий PROSEPT цвет сосна, ф/п 600мл',
    name_1c: 'Герметик акриловый цвет сосна, ф/п 600мл',
    wb_name:
      'Герметик акриловый для швов для деревянных домов, конструкций, изделий PROSEPT цвет сосна, ф/п 600мл',
    ozon_article: 189522735,
    wb_article: 150126217,
    ym_article: '0024-06-с',
    wb_article_td: ''
  },
  {
    FIELD1: 3,
    id: 147,
    article: '305-2',
    ean_13: 4610093420164,
    name: 'Кондиционер для белья с ароматом  королевского ИрисаCrystal Rinserконцентрат / 2 л ',
    cost: 157.73,
    recommended_price: 342,
    category_id: 29,
    ozon_name: 'Кондиционер для белья "Королевский Ирис" Prosept Crystal Rinser, 2 л.',
    name_1c: 'Кондиционер для белья "Королевский Ирис" Prosept Crystal Rinser, 2 л.',
    wb_name: 'Кондиционер для белья "Королевский Ирис" Prosept Crystal Rinser, 2 л.',
    ozon_article: 339377922,
    wb_article: 150032962,
    ym_article: '305-2',
    wb_article_td: ''
  },
  {
    FIELD1: 4,
    id: 502,
    article: '0024-7 б',
    ean_13: null,
    name: 'Герметик акриловой  цвет Белый, 7 кг',
    cost: null,
    recommended_price: null,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: 189522867,
    wb_article: 150126216,
    ym_article: '0024-7-б',
    wb_article_td: ''
  },
  {
    FIELD1: 5,
    id: 220,
    article: '051-6',
    ean_13: 4610093420607,
    name: 'Грунт БЕТОНКОНТАКТготовый состав / 6 кг',
    cost: 703,
    recommended_price: 1339,
    category_id: 26,
    ozon_name:
      'Грунт бетоноконтакт, для гладких поверхностей перед нанесением штукатурок, шпатлевок и плиточного клея, готовый состав, 6 кг',
    name_1c:
      'Грунт бетоноконтакт, для гладких поверхностей перед нанесением штукатурок, шпатлевок и плиточного клея, готовый состав, 6 кг',
    wb_name:
      'Грунт бетоноконтакт, для гладких поверхностей перед нанесением штукатурок, шпатлевок и плиточного клея, готовый состав, 6 кг',
    ozon_article: 453193200,
    wb_article: 149699633,
    ym_article: '051-6',
    wb_article_td: ''
  },
  {
    FIELD1: 6,
    id: 385,
    article: '051-10',
    ean_13: 4680008147998,
    name: 'Грунт БЕТОНКОНТАКТготовый состав / 12 кг',
    cost: 1111,
    recommended_price: 2505,
    category_id: 26,
    ozon_name:
      'Грунт бетоноконтакт, для гладких поверхностей перед нанесением штукатурок, шпатлевок и плиточного клея, готовый состав, 12 кг',
    name_1c:
      'Грунт бетоноконтакт, для гладких поверхностей перед нанесением штукатурок, шпатлевок и плиточного клея, готовый состав, 12 кг',
    wb_name:
      'Грунт бетоноконтакт, для гладких поверхностей перед нанесением штукатурок, шпатлевок и плиточного клея, готовый состав, 12 кг',
    ozon_article: 189522783,
    wb_article: 149699627,
    ym_article: '051-10',
    wb_article_td: ''
  },
  {
    FIELD1: 7,
    id: 114,
    article: '125-5',
    ean_13: 4680008141842,
    name: 'Средство для удаления технических масел, смазочных материалов и нефтепродуктовDuty Oil концентрат 1:20-1:150 /  5 л',
    cost: 711.82,
    recommended_price: 1663,
    category_id: 35,
    ozon_name:
      'Средство для удаления технических масел, смазочных материалов и нефтепродуктов PROSEPT Duty Oil, 5 л.',
    name_1c:
      'Средство для удаления технических масел, смазочных материалов и нефтепродуктов PROSEPT Duty Oil, 5 л.',
    wb_name:
      'Средство для удаления технических масел, смазочных материалов и нефтепродуктов PROSEPT Duty Oil, 5 л.',
    ozon_article: 189522869,
    wb_article: 149992148,
    ym_article: '125-5',
    wb_article_td: ''
  },
  {
    FIELD1: 8,
    id: 505,
    article: 'СФ001-5',
    ean_13: 4610093421024,
    name: 'Антисептик универсальный суперсильный',
    cost: 200,
    recommended_price: 510,
    category_id: 20,
    ozon_name: 'Антисептик универсальный суперсильный',
    name_1c: 'Антисептик универсальный суперсильный',
    wb_name: 'Антисептик универсальный суперсильный',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 9,
    id: 32,
    article: '100-1',
    ean_13: 4680008141705,
    name: 'Средство для мытья светлых полов с отбеливающим эффектомMultipower Whiteконцентрат 1:20-1:200 / 1 л',
    cost: 132.72,
    recommended_price: 311,
    category_id: 40,
    ozon_name:
      'Профессиональное средство для мытья светлых полов с отбеливающим эффектом PROSEPT Multipower White, 1 л.',
    name_1c:
      'Профессиональное средство для мытья светлых полов с отбеливающим эффектом PROSEPT Multipower White, 1 л.',
    wb_name:
      'Профессиональное средство для мытья светлых полов с отбеливающим эффектом PROSEPT Multipower White, 1 л.',
    ozon_article: 451088021,
    wb_article: 149705841,
    ym_article: '100-1',
    wb_article_td: ''
  },
  {
    FIELD1: 10,
    id: 241,
    article: '001-5',
    ean_13: 4680008140029,
    name: 'Отбеливатель для древесины PROSEPT 50концентрат 1:1 / 5 л',
    cost: 682,
    recommended_price: 1626,
    category_id: 35,
    ozon_name: 'Отбеливатель для древесины PROSEPT 50, концентрат, 5 л.',
    name_1c: 'Отбеливатель для древесины PROSEPT 50, концентрат, 5 л.',
    wb_name: 'Отбеливатель для древесины PROSEPT 50, концентрат, 5 л.',
    ozon_article: 189522702,
    wb_article: 149966030,
    ym_article: '001-5',
    wb_article_td: ''
  },
  {
    FIELD1: 11,
    id: 339,
    article: '040-9',
    ean_13: 4680008145987,
    name: 'Антисептик лессирующий BiO LASUR / тик / 9 л',
    cost: 2159,
    recommended_price: 5145,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / тик / 9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / тик / 9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / тик / 9 л',
    ozon_article: 577626084,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 12,
    id: 346,
    article: '038-09',
    ean_13: 4680008146144,
    name: 'Антисептик лессирующий BiO LASUR / махагон / 0,9 л',
    cost: 255,
    recommended_price: 607,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / махагон / 0,9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / махагон / 0,9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / махагон / 0,9 л',
    ozon_article: 577610937,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 13,
    id: 343,
    article: '034-09',
    ean_13: 4680008145994,
    name: 'Антисептик лессирующий BiO LASUR / лиственница / 0,9 л',
    cost: 255,
    recommended_price: 607,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / лиственница / 0,9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / лиственница / 0,9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / лиственница / 0,9 л',
    ozon_article: 577614089,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 14,
    id: 337,
    article: '040-09',
    ean_13: 4680008145963,
    name: 'Антисептик лессирующий BiO LASUR / тик / 0,9 л',
    cost: 255,
    recommended_price: 607,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / тик / 0,9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / тик / 0,9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / тик / 0,9 л',
    ozon_article: 577621671,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 15,
    id: 43,
    article: '284-08',
    ean_13: 4680008147196,
    name: 'Средство для мытья полов и стенMultipower "Полевые цветы"концентрат  1:10 – 1:120 / 0,8 л',
    cost: 77.94,
    recommended_price: 182,
    category_id: null,
    ozon_name: '',
    name_1c:
      'Средство для мытья полов и стенMultipower "Полевые цветы"концентрат  1:10 – 1:120 / 0,8 л',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 16,
    id: 338,
    article: '040-2',
    ean_13: 4680008145970,
    name: 'Антисептик лессирующий BiO LASUR / тик / 2,7 л',
    cost: 721,
    recommended_price: 1717,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / тик / 2,7 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / тик / 2,7 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / тик / 2,7 л',
    ozon_article: 577624042,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 17,
    id: 348,
    article: '038-9',
    ean_13: 4680008146168,
    name: 'Антисептик лессирующий BiO LASUR / махагон / 9 л',
    cost: 2159,
    recommended_price: 5145,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / махагон / 9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / махагон / 9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / махагон / 9 л',
    ozon_article: 577613095,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 18,
    id: 341,
    article: '036-2',
    ean_13: 4680008146120,
    name: 'Антисептик лессирующий BiO LASUR / дуб / 2,7 л',
    cost: 721,
    recommended_price: 1717,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / дуб / 2,7 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / дуб / 2,7 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / дуб / 2,7 л',
    ozon_article: 577620203,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 19,
    id: 352,
    article: '039-09',
    ean_13: 4680008146052,
    name: 'Антисептик лессирующий BiO LASUR / палисандр / 0,9 л',
    cost: 255,
    recommended_price: 607,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / палисандр / 0,9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / палисандр / 0,9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / палисандр / 0,9 л',
    ozon_article: 577514976,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 20,
    id: 353,
    article: '039-2',
    ean_13: 4680008146069,
    name: 'Антисептик лессирующий BiO LASUR / палисандр / 2,7 л',
    cost: 721,
    recommended_price: 1717,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / палисандр / 2,7 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / палисандр / 2,7 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / палисандр / 2,7 л',
    ozon_article: 577515287,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 21,
    id: 354,
    article: '039-9',
    ean_13: 4680008146076,
    name: 'Антисептик лессирующий BiO LASUR / палисандр / 9 л',
    cost: 2159,
    recommended_price: 5145,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / палисандр / 9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / палисандр / 9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / палисандр / 9 л',
    ozon_article: 577516280,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 22,
    id: 351,
    article: '037-9',
    ean_13: 4680008146045,
    name: 'Антисептик лессирующий BiO LASUR / орех / 9 л',
    cost: 2159,
    recommended_price: 5145,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / орех / 9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / орех / 9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / орех / 9 л',
    ozon_article: 577518230,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 23,
    id: 503,
    article: '0024-7 о',
    ean_13: null,
    name: '',
    cost: null,
    recommended_price: null,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: 150126213,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 24,
    id: 44,
    article: '283-08',
    ean_13: 4680008147172,
    name: 'Средство для мытья полов и стен Multipower "После дождя"концентрат 1:10 – 1:120 / 0,8 л',
    cost: 77.94,
    recommended_price: 182,
    category_id: null,
    ozon_name: '',
    name_1c:
      'Средство для мытья полов и стен Multipower "После дождя"концентрат 1:10 – 1:120 / 0,8 л',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 25,
    id: 84,
    article: '132-05',
    ean_13: 4680008145437,
    name: 'Гель для мытья  посуды вручную. Без запахаCookyконцентрированное средство / 0,5 л ',
    cost: 80,
    recommended_price: 174,
    category_id: 41,
    ozon_name: 'Гель для мытья  посуды вручную. Без запахаCookyконцентрированное средство / 0,5 л ',
    name_1c: 'Гель для мытья  посуды вручную. Без запахаCookyконцентрированное средство / 0,5 л ',
    wb_name: 'Гель для мытья  посуды вручную. Без запахаCookyконцентрированное средство / 0,5 л ',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 26,
    id: 55,
    article: '294-075',
    ean_13: 4680008147479,
    name: 'Средство усиленного действия для удаления ржавчины и минеральных отложенийBath Acid +  с ароматом цитрусаконцентрат 1:200-1:500 / 0,75 л',
    cost: 75,
    recommended_price: 176,
    category_id: 52,
    ozon_name:
      'Средство PROSEPT усиленного действия для удаления ржавчины и минеральных отложений Bath Acid +  с аромат цитруса. Концентрат. 0,75л',
    name_1c:
      'Средство PROSEPT усиленного действия для удаления ржавчины и минеральных отложений Bath Acid +  с аромат цитруса. Концентрат. 0,75л',
    wb_name:
      'Средство PROSEPT усиленного действия для удаления ржавчины и минеральных отложений Bath Acid +  с аромат цитруса. Концентрат. 0,75л',
    ozon_article: 413264552,
    wb_article: 149811030,
    ym_article: '294-075',
    wb_article_td: '294-0750'
  },
  {
    FIELD1: 27,
    id: 466,
    article: 'М014-12',
    ean_13: 4610093421062,
    name: 'Герметик акриловый  цвет медовый ф/п 600 мл. (12 штук )',
    cost: 3686.4,
    recommended_price: 7716.96,
    category_id: 25,
    ozon_name:
      'Герметик акриловый белый для швов для деревянных домов, конструкций, изделий PROSEPT цвет медовый ф/п 600 мл. (12 штук )',
    name_1c:
      'Герметик акриловый белый для швов для деревянных домов, конструкций, изделий PROSEPT цвет медовый ф/п 600 мл. (12 штук )',
    wb_name:
      'Герметик акриловый белый для швов для деревянных домов, конструкций, изделий PROSEPT цвет медовый ф/п 600 мл. (12 штук )',
    ozon_article: 189522826,
    wb_article: 161240422,
    ym_article: 'M014-12',
    wb_article_td: ''
  },
  {
    FIELD1: 28,
    id: 78,
    article: '143-20',
    ean_13: 4680008143457,
    name: 'Cредство для чистки коптильных камерCooky Smokeконцентрат 1:10-1:100 / 20 л',
    cost: 2781,
    recommended_price: 6496,
    category_id: 49,
    ozon_name: 'Cредство для чистки коптильных камерCooky Smokeконцентрат 1:10-1:100 / 20 л',
    name_1c: 'Cредство для чистки коптильных камерCooky Smokeконцентрат 1:10-1:100 / 20 л',
    wb_name: 'Cредство для чистки коптильных камерCooky Smokeконцентрат 1:10-1:100 / 20 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 29,
    id: 95,
    article: '300-5',
    ean_13: 4680008148179,
    name: 'Гель эконом-класса для мытья посуды вручную. С ароматом лимонаCooky Gel Lemon концентрированное средство / 5 л ',
    cost: 421,
    recommended_price: 914,
    category_id: 41,
    ozon_name:
      'Гель эконом-класса для мытья посуды вручную. С ароматом лимонаCooky Gel Lemon концентрированное средство / 5 л ',
    name_1c:
      'Гель эконом-класса для мытья посуды вручную. С ароматом лимонаCooky Gel Lemon концентрированное средство / 5 л ',
    wb_name:
      'Гель эконом-класса для мытья посуды вручную. С ароматом лимонаCooky Gel Lemon концентрированное средство / 5 л ',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 30,
    id: 183,
    article: '251-5/5',
    ean_13: 4680008145277,
    name: 'Антибактериальное мылоDiona Antibacготовое средство / 5 л ПЭТ',
    cost: 418,
    recommended_price: 907,
    category_id: 33,
    ozon_name: 'Антибактериальное мылоDiona Antibacготовое средство / 5 л ПЭТ',
    name_1c: 'Антибактериальное мылоDiona Antibacготовое средство / 5 л ПЭТ',
    wb_name: 'Антибактериальное мылоDiona Antibacготовое средство / 5 л ПЭТ',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 31,
    id: 118,
    article: '273-20',
    ean_13: null,
    name: 'Средство усиленного действия для чистки коптильных камерDuty Fogконцентрат / 20 л',
    cost: 3730,
    recommended_price: 8712,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 32,
    id: 119,
    article: '274-20',
    ean_13: null,
    name: 'Средство низкопенное  для  очистки  алюминия и сплавов на его основеDuty Mud  концентрат / 20 л',
    cost: 2818,
    recommended_price: 6581,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 33,
    id: 145,
    article: '296-2',
    ean_13: 4680008149985,
    name: 'Кондиционер для белья с ароматом лепестков СакурыCrystal Rinserконцентрат / 2 л ',
    cost: 163.91,
    recommended_price: 355,
    category_id: 29,
    ozon_name: 'Кондиционер для белья "Лепестки Сакуры" PROSEPT Crystal Rinser, 2 л.',
    name_1c: 'Кондиционер для белья "Лепестки Сакуры" PROSEPT Crystal Rinser, 2 л.',
    wb_name: 'Кондиционер для белья "Лепестки Сакуры" PROSEPT Crystal Rinser, 2 л.',
    ozon_article: 338908451,
    wb_article: 150032961,
    ym_article: '296-2',
    wb_article_td: ''
  },
  {
    FIELD1: 34,
    id: 506,
    article: 'М001-3',
    ean_13: 4610093420973,
    name: 'Набор для посудомоечной посуды PROSEPT, 3 средства',
    cost: 638,
    recommended_price: 1489,
    category_id: null,
    ozon_name: 'Набор для посудомоечной посуды PROSEPT, 3 средства',
    name_1c: 'Набор для посудомоечной машины PROSEPT, 3 средства',
    wb_name: 'Набор для посудомоечной посуды Splash, 3 средства',
    ozon_article: 461916238,
    wb_article: 150666267,
    ym_article: 'М001-3',
    wb_article_td: ''
  },
  {
    FIELD1: 35,
    id: 504,
    article: 'w022-05',
    ean_13: null,
    name: '',
    cost: null,
    recommended_price: null,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 36,
    id: 134,
    article: '217-1',
    ean_13: 4680008143846,
    name: 'Стиральный порошок для белых тканейCrystal White / 5 кг ПЭТ',
    cost: 704,
    recommended_price: 1645,
    category_id: 54,
    ozon_name: 'Стиральный порошок для белых тканейCrystal White / 5 кг ПЭТ',
    name_1c: 'Стиральный порошок для белых тканейCrystal White / 5 кг ПЭТ',
    wb_name: 'Стиральный порошок для белых тканейCrystal White / 5 кг ПЭТ',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 37,
    id: 507,
    article: 'М002-6',
    ean_13: 4610093420959,
    name: 'Набор для стирки PROSEPT, 6 средств для всех типов тканей',
    cost: 1109,
    recommended_price: 2589,
    category_id: null,
    ozon_name: 'Набор для стирки PROSEPT, 6 средств для всех типов тканей',
    name_1c: 'Набор для стирки PROSEPT, 6 средств для всех типов тканей',
    wb_name: 'Набор для стирки PROSEPT, 6 средств для всех типов тканей',
    ozon_article: 461877062,
    wb_article: 150665521,
    ym_article: 'М002-6',
    wb_article_td: ''
  },
  {
    FIELD1: 38,
    id: 483,
    article: 'М018-2',
    ean_13: 4610093421222,
    name: 'Набор Удалитель мха, концентрат 1 л, 2 шт',
    cost: 482,
    recommended_price: 1102,
    category_id: null,
    ozon_name: 'Набор Удалитель мха, концентрат 1 л, 2 шт',
    name_1c: 'Набор Удалитель мха, концентрат 1 л, 2 шт',
    wb_name: 'Набор Удалитель мха, концентрат 1 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 39,
    id: 508,
    article: 'М003-2',
    ean_13: 4610093420980,
    name: 'Набор для посудомоечной посуды PROSEPT, 2 средства (гель и ополаскиватель)',
    cost: 512,
    recommended_price: 1195,
    category_id: null,
    ozon_name: 'Набор для посудомоечной посуды PROSEPT, 2 средства (гель и ополаскиватель)',
    name_1c: 'Набор для посудомоечной машины PROSEPT, 2 средства',
    wb_name: 'Набор для посудомоечной посуды Splash, гель и ополаскиватель',
    ozon_article: 463666869,
    wb_article: 150666268,
    ym_article: 'М003-2',
    wb_article_td: ''
  },
  {
    FIELD1: 40,
    id: 437,
    article: '0024-06 б',
    ean_13: 4680008145192,
    name: 'Герметик акриловый цвет белый, ф/п 600 мл.',
    cost: 307.2,
    recommended_price: 643.08,
    category_id: 25,
    ozon_name:
      'Герметик акриловый белый для швов для деревянных домов, конструкций, изделий PROSEPT, ф/п 600 мл.',
    name_1c: 'Герметик акриловый цвет белый, ф/п 600 мл.',
    wb_name:
      'Герметик акриловый белый для швов для деревянных домов, конструкций, изделий PROSEPT, ф/п 600 мл.',
    ozon_article: 189522732,
    wb_article: 150126210,
    ym_article: '0024-06-б',
    wb_article_td: ''
  },
  {
    FIELD1: 41,
    id: 295,
    article: '006-10',
    ean_13: 4680008140210,
    name: 'Огнебиозащита ОГНЕБИО PROF 2 группа бесцветный готовый состав / 10 л',
    cost: 425,
    recommended_price: 1012,
    category_id: 38,
    ozon_name: 'Огнебиозащита для древесины PROSEPT ОГНЕБИО PROF  2-ая группа, 10л.',
    name_1c: 'Огнебиозащита для древесины PROSEPT ОГНЕБИО PROF  2-ая группа, 10л.',
    wb_name: 'Огнебиозащита для древесины PROSEPT ОГНЕБИО PROF  2-ая группа, 10л.',
    ozon_article: 189522835,
    wb_article: 154127918,
    ym_article: '006-10',
    wb_article_td: ''
  },
  {
    FIELD1: 42,
    id: 509,
    article: 'М004-2',
    ean_13: 4610093420997,
    name: 'Набор для посудомоечной посуды PROSEPT, 2 средства (ополаскиватель и соль)',
    cost: 322,
    recommended_price: 752,
    category_id: null,
    ozon_name: 'Набор для посудомоечной посуды PROSEPT, 2 средства (ополаскиватель и соль)',
    name_1c: 'Набор для посудомоечной машины - 1 PROSEPT, 2 средства',
    wb_name: 'Набор для посудомоечной посуды Splash, ополаскиватель и соль',
    ozon_article: 463671331,
    wb_article: 150666269,
    ym_article: 'М004-2',
    wb_article_td: ''
  },
  {
    FIELD1: 43,
    id: 510,
    article: 'М005-2',
    ean_13: 4610093421000,
    name: 'Набор "Антиплесень" PROSEPT (удалитель плесени и защита от плесени)',
    cost: 354,
    recommended_price: 827,
    category_id: null,
    ozon_name: 'Набор "Антиплесень" PROSEPT (удалитель плесени и защита от плесени)',
    name_1c: 'Набор "Антиплесень" PROSEPT (удалитель плесени и защита от плесени)',
    wb_name: 'Набор "Антиплесень" :удалитель плесени и защита от плесени',
    ozon_article: 463682015,
    wb_article: 150668683,
    ym_article: 'М005-2',
    wb_article_td: ''
  },
  {
    FIELD1: 44,
    id: 177,
    article: '141-5/5',
    ean_13: 4680008143921,
    name: 'жидкое гель-мыло эконом-класса. C ароматом яблокаDiona Apple Eготовое средство / 5 л ПЭТ',
    cost: 176.86,
    recommended_price: 384,
    category_id: 33,
    ozon_name:
      'жидкое гель-мыло эконом-класса. C ароматом яблокаDiona Apple Eготовое средство / 5 л ПЭТ',
    name_1c:
      'жидкое гель-мыло эконом-класса. C ароматом яблокаDiona Apple Eготовое средство / 5 л ПЭТ',
    wb_name:
      'жидкое гель-мыло эконом-класса. C ароматом яблокаDiona Apple Eготовое средство / 5 л ПЭТ',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 45,
    id: 187,
    article: 'D1 01050',
    ean_13: 4680008148605,
    name: 'Кожный антисептик ПРОФ ДЗ "PROF DZ" готовый состав / 0,05 л',
    cost: 44,
    recommended_price: 0,
    category_id: 21,
    ozon_name: 'Кожный антисептик ПРОФ ДЗ "PROF DZ" готовый состав / 0,05 л',
    name_1c: 'Кожный антисептик ПРОФ ДЗ "PROF DZ" готовый состав / 0,05 л',
    wb_name: 'Кожный антисептик ПРОФ ДЗ "PROF DZ" готовый состав / 0,05 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 46,
    id: 182,
    article: 'P1 11005',
    ean_13: null,
    name: 'Cредство для рук гигиеническое с антибактериальным эффектом PROSEPT готовый состав / 5 л',
    cost: 565,
    recommended_price: 1319,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 47,
    id: 181,
    article: 'P1 11800',
    ean_13: null,
    name: 'Cредство для рук гигиеническое с антибактериальным эффектом PROSEPT готовый состав / 0,8 л',
    cost: 155,
    recommended_price: 361,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 48,
    id: 512,
    article: 'М009-2',
    ean_13: 4610093421192,
    name: 'Средство для мытья полов PROSEPT Multipower "Вершины Тибета", 2 штуки*0.8 л.',
    cost: 156,
    recommended_price: 364,
    category_id: null,
    ozon_name: 'Средство для мытья полов PROSEPT Multipower "Вершины Тибета", 2 штуки*0.8 л.',
    name_1c: 'Набор средств для мытья полов PROSEPT Multipower "Вершины Тибета", 800 мл, 2 шт.',
    wb_name: '',
    ozon_article: 451196851,
    wb_article: null,
    ym_article: 'М009-2',
    wb_article_td: ''
  },
  {
    FIELD1: 49,
    id: 179,
    article: '222-5',
    ean_13: 4680008143815,
    name: 'Пенное мыло для дозаторов. Без красителей и ароматизаторовDiona Flowerконцентрат / 5 л ',
    cost: 465.74,
    recommended_price: 848,
    category_id: 33,
    ozon_name:
      'Пенное мыло для дозаторов. Без красителей и ароматизаторовDiona Flowerконцентрат / 5 л ',
    name_1c:
      'Пенное мыло для дозаторов. Без красителей и ароматизаторовDiona Flowerконцентрат / 5 л ',
    wb_name:
      'Пенное мыло для дозаторов. Без красителей и ароматизаторовDiona Flowerконцентрат / 5 л ',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 50,
    id: 511,
    article: 'М006-2',
    ean_13: 4610093421017,
    name: 'Набор для удаления загрязнений и наклеек PROSEPT, 2 средства (универсальный спрей для уборки и удалитель наклеек)',
    cost: 284,
    recommended_price: 664,
    category_id: null,
    ozon_name:
      'Набор для удаления загрязнений и наклеек PROSEPT, 2 средства (универсальный спрей для уборки и удалитель наклеек)',
    name_1c: 'Набор для удаления загрязнений и наклеек PROSEPT',
    wb_name: 'Набор для удаления загрязнений и наклеек , 2 средства',
    ozon_article: 464002480,
    wb_article: 150654375,
    ym_article: 'М006-2',
    wb_article_td: ''
  },
  {
    FIELD1: 51,
    id: 484,
    article: 'М019-2',
    ean_13: 4610093421239,
    name: 'Набор Удалитель мха, готовый состав, 1 л, 2 шт',
    cost: 400,
    recommended_price: 915,
    category_id: null,
    ozon_name: 'Набор Удалитель мха, готовый состав, 1 л, 2 шт',
    name_1c: 'Набор Удалитель мха, готовый состав, 1 л, 2 шт',
    wb_name: 'Набор Удалитель мха, готовый состав, 1 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 52,
    id: 132,
    article: '151-2',
    ean_13: 4680008142399,
    name: 'Средство для удаления граффити, маркера, краскиDuty Graffiti Maxготовый состав, аэрозоль / 2 л',
    cost: 1436.86,
    recommended_price: 3356,
    category_id: 40,
    ozon_name: 'Средство для удаления граффити PROSEPT DUTY GRAFFITI MAX, 2 л.',
    name_1c: 'Средство для удаления граффити PROSEPT DUTY GRAFFITI MAX, 2 л.',
    wb_name: 'Средство для удаления граффити PROSEPT DUTY GRAFFITI MAX, 2 л.',
    ozon_article: 451973852,
    wb_article: 149705845,
    ym_article: '151-2',
    wb_article_td: ''
  },
  {
    FIELD1: 53,
    id: 298,
    article: '006-10к',
    ean_13: 4680008141262,
    name: 'Огнебиозащита ОГНЕБИО PROF 2 группа, красный готовый состав / 10 л',
    cost: 425,
    recommended_price: 1012,
    category_id: 38,
    ozon_name:
      'Огнебиозащита для древесины PROSEPT ОГНЕБИО PROF 2-ая группа, с цветовой индикацией, 10л.',
    name_1c:
      'Огнебиозащита для древесины PROSEPT ОГНЕБИО PROF 2-ая группа, с цветовой индикацией, 10л.',
    wb_name:
      'Огнебиозащита для древесины PROSEPT ОГНЕБИО PROF 2-ая группа, с цветовой индикацией, 10л.',
    ozon_article: 236737462,
    wb_article: 150127571,
    ym_article: '006-10к',
    wb_article_td: ''
  },
  {
    FIELD1: 54,
    id: 164,
    article: '259-04',
    ean_13: 4680008146410,
    name: 'Чистящее средство, сода эффектCrystal Handготовый состав / 0,4 л',
    cost: 53,
    recommended_price: 98,
    category_id: 56,
    ozon_name: 'Чистящее средство, сода эффектCrystal Handготовый состав / 0,4 л',
    name_1c: 'Чистящее средство, сода эффектCrystal Handготовый состав / 0,4 л',
    wb_name: 'Чистящее средство, сода эффектCrystal Handготовый состав / 0,4 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 55,
    id: 249,
    article: '061-1',
    ean_13: 4680008148834,
    name: 'Антисептик невымываемыйPROSEPT ULTRAкоричневый концентрат 1:10 / 1 л',
    cost: 360,
    recommended_price: 858,
    category_id: 20,
    ozon_name: 'Антисептик невымываемый PROSEPT ULTRA, коричневый, концентрат, 1 л.',
    name_1c: 'Антисептик невымываемый PROSEPT ULTRA, коричневый, концентрат, 1 л.',
    wb_name: 'Антисептик невымываемый PROSEPT ULTRA, коричневый, концентрат, 1 л.',
    ozon_article: 253565303,
    wb_article: 150033485,
    ym_article: '061-1',
    wb_article_td: ''
  },
  {
    FIELD1: 56,
    id: 263,
    article: '004-1',
    ean_13: 4680008140128,
    name: 'Антисептик для внутренних работPROSEPT SAUNAконцентрат 1:10 / 1 л',
    cost: 317,
    recommended_price: 755,
    category_id: 20,
    ozon_name: 'Антисептик для бани и сауны PROSEPT SAUNA, концентрат, 1 л.',
    name_1c: 'Антисептик для бани и сауны PROSEPT SAUNA, концентрат, 1 л.',
    wb_name: 'Антисептик для бани и сауны PROSEPT SAUNA, концентрат, 1 л.',
    ozon_article: 189522710,
    wb_article: 150033018,
    ym_article: '004-1',
    wb_article_td: ''
  },
  {
    FIELD1: 57,
    id: 206,
    article: '221-1',
    ean_13: null,
    name: 'ПеногасительAntifoam концентрат до 1:300 / 1 л ',
    cost: 365,
    recommended_price: 853,
    category_id: null,
    ozon_name: '',
    name_1c: 'ПеногасительAntifoam концентрат до 1:300 / 1 л ',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 58,
    id: 485,
    article: 'М024-2',
    ean_13: 4610093421420,
    name: 'Набор Краска для OSB плит TopTex, 1 кг, 2 шт',
    cost: 358,
    recommended_price: 718,
    category_id: null,
    ozon_name: 'Набор Краска для OSB плит TopTex, 1 кг, 2 шт',
    name_1c: 'Набор Краска для OSB плит TopTex, 1 кг, 2 шт',
    wb_name: 'Набор Краска для OSB плит TopTex, 1 кг, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 59,
    id: 189,
    article: 'D1 01001',
    ean_13: 4610093420034,
    name: 'Кожный антисептик ПРОФ ДЗ "PROF DZ"готовый состав / 1 л',
    cost: 240,
    recommended_price: 0,
    category_id: 21,
    ozon_name: 'Кожный антисептик PROSEPT PROF DZ, 1 л.',
    name_1c: 'Кожный антисептик PROSEPT PROF DZ, 1 л.',
    wb_name: 'Кожный антисептик PROSEPT PROF DZ, 1 л.',
    ozon_article: null,
    wb_article: 150119534,
    ym_article: 'D1-01001',
    wb_article_td: ''
  },
  {
    FIELD1: 60,
    id: 186,
    article: 'P1 06005',
    ean_13: null,
    name: 'Жидкое мыло с антибактериальным компонентом для диспенсеров с пенообразователемDiona AN FOAM / 5 л',
    cost: 492,
    recommended_price: 1067,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 61,
    id: 222,
    article: '0024-06т',
    ean_13: null,
    name: 'Герметик акриловый цвет тик, ф/п 600мл',
    cost: 376,
    recommended_price: 643,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет тик, ф/п 600мл',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 62,
    id: 513,
    article: 'М011-2',
    ean_13: 4610093421154,
    name: 'Средство для мытья полов PROSEPT Multipower "После дождя", 2 штуки*0.8 л.',
    cost: 156,
    recommended_price: 364,
    category_id: null,
    ozon_name: 'Средство для мытья полов PROSEPT Multipower "После дождя", 2 штуки*0.8 л.',
    name_1c: 'Набор средств для мытья полов PROSEPT Multipower "После дождя" 2 шт.',
    wb_name: '',
    ozon_article: 451255728,
    wb_article: null,
    ym_article: 'М011-2',
    wb_article_td: ''
  },
  {
    FIELD1: 63,
    id: 487,
    article: 'М023-2',
    ean_13: 4610093421284,
    name: 'Набор Очиститель фасадов SALT CLEANER, 1 л, 2 шт',
    cost: 516,
    recommended_price: 1177,
    category_id: null,
    ozon_name: 'Набор Очиститель фасадов SALT CLEANER, 1 л, 2 шт',
    name_1c: 'Набор Очиститель фасадов SALT CLEANER, 1 л, 2 шт',
    wb_name: 'Набор Очиститель фасадов SALT CLEANER, 1 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 64,
    id: 488,
    article: 'М025-2',
    ean_13: 4610093421291,
    name: 'Набор Universal Hard спрей, 0.5 л, 2 шт',
    cost: 187.52,
    recommended_price: 422,
    category_id: null,
    ozon_name: 'Набор Universal Hard спрей, 0.5 л, 2 шт',
    name_1c: 'Набор Universal Hard спрей, 0.5 л, 2 шт',
    wb_name: 'Набор Universal Hard спрей, 0.5 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 65,
    id: 470,
    article: 'М012-2',
    ean_13: 4610093421185,
    name: 'Концентрат для мытья полов и стен Multipower "Цитрус" 0,8 л',
    cost: 156,
    recommended_price: 364,
    category_id: 50,
    ozon_name: 'Средство для мытья полов PROSEPT Multipower "Цитрус", 2 штуки*0.8 л.',
    name_1c: 'Средство для мытья полов PROSEPT Multipower "Цитрус", 2 штуки*0.8 л.',
    wb_name: 'Средство для мытья полов PROSEPT Multipower "Цитрус", 2 штуки*0.8 л.',
    ozon_article: 451210414,
    wb_article: null,
    ym_article: 'М012-2',
    wb_article_td: ''
  },
  {
    FIELD1: 66,
    id: 300,
    article: '006-65к',
    ean_13: 4680008143891,
    name: 'Огнебиозащита ОГНЕБИО PROF 2 группа, красный готовый состав / 65 л',
    cost: 3276,
    recommended_price: 7806,
    category_id: 38,
    ozon_name:
      'Огнебиозащита для древесиныPROSEPT ОГНЕБИО PROF2 группа, красный готовый состав / 65 л',
    name_1c:
      'Огнебиозащита для древесиныPROSEPT ОГНЕБИО PROF2 группа, красный готовый состав / 65 л',
    wb_name:
      'Огнебиозащита для древесиныPROSEPT ОГНЕБИО PROF2 группа, красный готовый состав / 65 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 67,
    id: 315,
    article: '063-65И',
    ean_13: null,
    name: 'ОГНЕБИОЗАЩИТА I группа, красный готовый состав / 65 кг',
    cost: 5452,
    recommended_price: 9868,
    category_id: 38,
    ozon_name: '',
    name_1c: 'ОГНЕБИОЗАЩИТА I группа, красный готовый состав / 65 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 68,
    id: 489,
    article: 'М032-2',
    ean_13: 4610093421307,
    name: 'Набор Duty Universal, 0.4 л, 2 шт',
    cost: 525,
    recommended_price: 1177,
    category_id: null,
    ozon_name: 'Набор Duty Universal, 0.4 л, 2 шт',
    name_1c: 'Набор Duty Universal, 0.4 л, 2 шт',
    wb_name: 'Набор Duty Universal, 0.4 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 69,
    id: 490,
    article: 'М026-2',
    ean_13: 4610093421314,
    name: 'Набор Flox Prof спрей, 0.5 л, 2 шт',
    cost: 253.34,
    recommended_price: 566,
    category_id: null,
    ozon_name: 'Набор Flox Prof спрей, 0.5 л, 2 шт',
    name_1c: 'Набор Flox Prof спрей, 0.5 л, 2 шт',
    wb_name: 'Набор Flox Prof спрей, 0.5 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 70,
    id: 491,
    article: 'М027-2',
    ean_13: 4610093421321,
    name: 'Набор Лак яхтный, глянцевый, 0.9 л, 2 шт',
    cost: 744,
    recommended_price: 1699,
    category_id: null,
    ozon_name: 'Набор Лак яхтный, глянцевый, 0.9 л, 2 шт',
    name_1c: 'Набор Лак яхтный, глянцевый, 0.9 л, 2 шт',
    wb_name: 'Набор Лак яхтный, глянцевый, 0.9 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 71,
    id: 492,
    article: 'М028-2',
    ean_13: 4610093421338,
    name: 'Набор Лак яхтный, полуматовый, 0.9 л, 2 шт',
    cost: 756,
    recommended_price: 1728,
    category_id: null,
    ozon_name: 'Набор Лак яхтный, полуматовый, 0.9 л, 2 шт',
    name_1c: 'Набор Лак яхтный, полуматовый, 0.9 л, 2 шт',
    wb_name: 'Набор Лак яхтный, полуматовый, 0.9 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 72,
    id: 358,
    article: '035-09',
    ean_13: 4680008146083,
    name: 'Антисептик лессирующий BiO LASUR / бук / 0,9 л',
    cost: 255,
    recommended_price: 607,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / бук / 0,9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / бук / 0,9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / бук / 0,9 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 73,
    id: 349,
    article: '037-09',
    ean_13: 4680008146021,
    name: 'Антисептик лессирующий BiO LASUR / орех / 0,9 л',
    cost: 255,
    recommended_price: 607,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / орех / 0,9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / орех / 0,9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / орех / 0,9 л',
    ozon_article: 577517368,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 74,
    id: 345,
    article: '034-9',
    ean_13: 4680008146014,
    name: 'Антисептик лессирующий BiO LASUR / лиственница / 9 л',
    cost: 2159,
    recommended_price: 5145,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / лиственница / 9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / лиственница / 9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / лиственница / 9 л',
    ozon_article: 577617874,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 75,
    id: 340,
    article: '036-09',
    ean_13: 4680008146113,
    name: 'Антисептик лессирующий BiO LASUR / дуб / 0,9 л',
    cost: 255,
    recommended_price: 607,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / дуб / 0,9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / дуб / 0,9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / дуб / 0,9 л',
    ozon_article: 577619513,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 76,
    id: 342,
    article: '036-9',
    ean_13: 4680008146137,
    name: 'Антисептик лессирующий BiO LASUR / дуб / 9 л',
    cost: 2159,
    recommended_price: 5145,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / дуб / 9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / дуб / 9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / дуб / 9 л',
    ozon_article: 577620641,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 77,
    id: 364,
    article: '0024-15б',
    ean_13: null,
    name: 'Герметик акриловый цвет Белый, 15 кг',
    cost: 4561.2,
    recommended_price: 9467,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет Белый, 15 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 78,
    id: 362,
    article: '0024-3б',
    ean_13: null,
    name: 'Герметик акриловый цвет Белый, 3 кг',
    cost: 1251,
    recommended_price: 2145,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет Белый, 3 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 79,
    id: 356,
    article: '033-2',
    ean_13: 4680008145918,
    name: 'Антисептик лессирующий BiO LASUR / сосна / 2,7 л',
    cost: 721,
    recommended_price: 1717,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / сосна / 2,7 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / сосна / 2,7 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / сосна / 2,7 л',
    ozon_article: 577436178,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 80,
    id: 496,
    article: 'М033-2',
    ean_13: 4610093421406,
    name: 'Набор Шпатлевка для OSB Proplast 1,3 кг, 2 шт',
    cost: 366,
    recommended_price: 732,
    category_id: null,
    ozon_name: 'Набор Шпатлевка для OSB Proplast 1,3 кг, 2 шт',
    name_1c: 'Набор Шпатлевка для OSB Proplast 1,3 кг, 2 шт',
    wb_name: 'Набор Шпатлевка для OSB Proplast 1,3 кг, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 81,
    id: 373,
    article: '0024-06о',
    ean_13: null,
    name: 'Герметик акриловый цвет Орех 0,6 л',
    cost: 326,
    recommended_price: 643,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет Орех 0,6 л',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 82,
    id: 376,
    article: '0024-15о',
    ean_13: null,
    name: 'Герметик акриловый цвет Орех, 15 кг',
    cost: 4561.2,
    recommended_price: 9467,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет Орех, 15 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 83,
    id: 374,
    article: '0024-3о',
    ean_13: null,
    name: 'Герметик акриловый цвет Орех, 3 кг',
    cost: 1251,
    recommended_price: 2145,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет Орех, 3 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 84,
    id: 370,
    article: '0024-3с',
    ean_13: null,
    name: 'Герметик акриловый цвет Сосна, 3 кг',
    cost: 1251,
    recommended_price: 2145,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет Сосна, 3 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 85,
    id: 493,
    article: 'М029-2',
    ean_13: 4610093421352,
    name: 'Набор Duty Leather, 0.4 л, 2 шт',
    cost: 207.36,
    recommended_price: 462,
    category_id: null,
    ozon_name: 'Набор Duty Leather, 0.4 л, 2 шт',
    name_1c: 'Набор Duty Leather, 0.4 л, 2 шт',
    wb_name: 'Набор Duty Leather, 0.4 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 86,
    id: 494,
    article: 'М030-2',
    ean_13: 4610093421383,
    name: 'Набор DUTY GRAFFITI, 0.4 л, 2 шт',
    cost: 415.04,
    recommended_price: 930,
    category_id: null,
    ozon_name: 'Набор DUTY GRAFFITI, 0.4 л, 2 шт',
    name_1c: 'Набор DUTY GRAFFITI, 0.4 л, 2 шт',
    wb_name: 'Набор DUTY GRAFFITI, 0.4 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 87,
    id: 495,
    article: 'М031-2',
    ean_13: 4610093421390,
    name: 'Набор Шпатлевка-замазка трещин Plastix 1,4 кг, 2 шт',
    cost: 388,
    recommended_price: 775,
    category_id: null,
    ozon_name: 'Набор Шпатлевка-замазка трещин Plastix 1,4 кг, 2 шт',
    name_1c: 'Набор Шпатлевка-замазка трещин Plastix 1,4 кг, 2 шт',
    wb_name: 'Набор Шпатлевка-замазка трещин Plastix 1,4 кг, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 88,
    id: 446,
    article: '0024-06 б12',
    ean_13: null,
    name: 'Герметик акриловый цвет белый ф/п 600 мл. (12 штук )',
    cost: 3686.4,
    recommended_price: 7716.96,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет белый ф/п 600 мл. (12 штук )',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 89,
    id: 2,
    article: '242-6',
    ean_13: 4610093420454,
    name: 'Антигололед - 32 PROSEPTготовый состав / 6 кг',
    cost: 220.39,
    recommended_price: 515,
    category_id: null,
    ozon_name: '',
    name_1c: 'Антигололед - 32 PROSEPTготовый состав / 6 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 90,
    id: 435,
    article: '284-08-2',
    ean_13: null,
    name: 'Концентрат для мытья полов и стен  Multipower "Полевые цветы" 0,8 л 2ШТ',
    cost: 156,
    recommended_price: 364,
    category_id: null,
    ozon_name: '',
    name_1c: 'Набор 2 шт Концентрат для мытья полов и стен  Multipower "Полевые цветы" 0,8 л',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 91,
    id: 434,
    article: '291-08-2',
    ean_13: null,
    name: 'Концентрат для мытья полов и стен Multipower "Цитрус" 0,8 л 2 ШТ',
    cost: 156,
    recommended_price: 364,
    category_id: null,
    ozon_name: '',
    name_1c: 'Набор Концентрат для мытья полов и стен Multipower "Цитрус" 0,8 л 2 ШТ',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 92,
    id: 497,
    article: 'М035-2',
    ean_13: 4610093421345,
    name: 'Отбеливатель Prosept 50, концентрат, 1 л, 2 шт',
    cost: 440,
    recommended_price: 1005,
    category_id: null,
    ozon_name: 'Отбеливатель Prosept 50, концентрат, 1 л, 2 шт',
    name_1c: 'Отбеливатель Prosept 50, концентрат, 1 л, 2 шт',
    wb_name: 'Отбеливатель Prosept 50, концентрат, 1 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 93,
    id: 447,
    article: '0024-06 с12',
    ean_13: null,
    name: 'Герметик акриловый цвет сосна, ф/п 600мл (12 штук )',
    cost: 3686.4,
    recommended_price: 7716.96,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет сосна, ф/п 600мл (12 штук )',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 94,
    id: 366,
    article: '0024-3м',
    ean_13: null,
    name: 'Герметик акриловый цвет Медовый, 3 кг',
    cost: 1251,
    recommended_price: 2145,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет Медовый, 3 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 95,
    id: 426,
    article: '071-12',
    ean_13: 4680008149756,
    name: 'Краска резиновая зеленый мох Ral 6005 / 12 кг',
    cost: 3206,
    recommended_price: 6711,
    category_id: 30,
    ozon_name: 'Краска резиновая PROSEPT SuperRubberзеленый мох Ral 6005 / 12 кг',
    name_1c: 'Краска резиновая зеленый мох Ral 6005 / 12 кг',
    wb_name: 'Краска резиновая PROSEPT SuperRubberзеленый мох Ral 6005 / 12 кг',
    ozon_article: 575100747,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 96,
    id: 498,
    article: 'М036-2',
    ean_13: 4610093421376,
    name: 'Антисептик ULTRA, концентрат, 1 л, 2 шт',
    cost: 720,
    recommended_price: 1645,
    category_id: null,
    ozon_name: 'Антисептик ULTRA, концентрат, 1 л, 2 шт',
    name_1c: 'Антисептик ULTRA, концентрат, 1 л, 2 шт',
    wb_name: 'Антисептик ULTRA, концентрат, 1 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 97,
    id: 42,
    article: '282-08',
    ean_13: 4680008147165,
    name: 'Средство для мытья полов и стен Multipower  "Вершины Тибета"концентрат  1:10 – 1:120 / 0,8 л',
    cost: 77.94,
    recommended_price: 182,
    category_id: null,
    ozon_name: '',
    name_1c:
      'Средство для мытья полов и стен Multipower  "Вершины Тибета"концентрат  1:10 – 1:120 / 0,8 л',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 98,
    id: 436,
    article: 'Р1 09005',
    ean_13: 4680008148353,
    name: '   ',
    cost: 500,
    recommended_price: 600,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 99,
    id: 248,
    article: '008-30',
    ean_13: 4680008140692,
    name: 'Антисептик невымываемый PROSEPT ULTRAконцентрат  1:10  / 30 л',
    cost: 8011,
    recommended_price: 14980,
    category_id: 20,
    ozon_name: 'Антисептик невымываемый PROSEPT ULTRAконцентрат  1:10  / 30 л',
    name_1c: 'Антисептик невымываемый PROSEPT ULTRAконцентрат  1:10  / 30 л',
    wb_name: 'Антисептик невымываемый PROSEPT ULTRAконцентрат  1:10  / 30 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 100,
    id: 102,
    article: '307-20',
    ean_13: 4680008148780,
    name: 'Средство для мытья посуды в посудомоечной машине. Для жесткой водыCooky Splash Hard концентрат 1:200-1:2000 / 20 л',
    cost: 3345.93,
    recommended_price: 7256,
    category_id: 42,
    ozon_name:
      'Средство для мытья посуды в посудомоечной машине. Для жесткой водыCooky Splash Hard концентрат 1:200-1:2000 / 20 л',
    name_1c:
      'Средство для мытья посуды в посудомоечной машине. Для жесткой водыCooky Splash Hard концентрат 1:200-1:2000 / 20 л',
    wb_name:
      'Средство для мытья посуды в посудомоечной машине. Для жесткой водыCooky Splash Hard концентрат 1:200-1:2000 / 20 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 101,
    id: 372,
    article: '0024-15с',
    ean_13: null,
    name: 'Герметик акриловый цвет Сосна, 15 кг',
    cost: 5428,
    recommended_price: 9467,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет Сосна, 15 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 102,
    id: 433,
    article: 'D1 01050-3',
    ean_13: null,
    name: 'Кожный антисептик PROF DZ готовый состав / 0,1 л',
    cost: 112.8,
    recommended_price: 226,
    category_id: null,
    ozon_name: '',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: 150119529,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 103,
    id: 359,
    article: '035-2',
    ean_13: 4680008146090,
    name: 'Антисептик лессирующий BiO LASUR / бук / 2,7 л',
    cost: 721,
    recommended_price: 1717,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / бук / 2,7 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / бук / 2,7 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / бук / 2,7 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 104,
    id: 256,
    article: '002-30',
    ean_13: 4680008140593,
    name: 'Антисептик трудновымываемый для наружных работ PROSEPT EXTERIORконцентрат 1:19 / 30 л',
    cost: 6198,
    recommended_price: 11589,
    category_id: 20,
    ozon_name:
      'Антисептик трудновымываемый для наружных работ PROSEPT EXTERIORконцентрат 1:19 / 30 л',
    name_1c:
      'Антисептик трудновымываемый для наружных работ PROSEPT EXTERIORконцентрат 1:19 / 30 л',
    wb_name:
      'Антисептик трудновымываемый для наружных работ PROSEPT EXTERIORконцентрат 1:19 / 30 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 105,
    id: 365,
    article: '0024-06м',
    ean_13: null,
    name: 'Герметик акриловый цвет Медовый 0,6 л',
    cost: 326,
    recommended_price: 643,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет Медовый 0,6 л',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 106,
    id: 262,
    article: '005-30',
    ean_13: 4680008140654,
    name: 'Антисептик универсальный для наружных и внутренних работPROSEPT UNIVERSALконцентрат 1:10 / 30 л',
    cost: 6695,
    recommended_price: 12199,
    category_id: 20,
    ozon_name:
      'Антисептик универсальный для наружных и внутренних работPROSEPT UNIVERSALконцентрат 1:10 / 30 л',
    name_1c:
      'Антисептик универсальный для наружных и внутренних работPROSEPT UNIVERSALконцентрат 1:10 / 30 л',
    wb_name:
      'Антисептик универсальный для наружных и внутренних работPROSEPT UNIVERSALконцентрат 1:10 / 30 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 107,
    id: 411,
    article: '065-20',
    ean_13: 4680008149930,
    name: 'Антисептик невымываемый ХМ-11, ГОСТ / 20 л',
    cost: 1020,
    recommended_price: 2135,
    category_id: 20,
    ozon_name: 'Антисептик невымываемый ХМ-11, ГОСТ / 20 л',
    name_1c: 'Антисептик невымываемый ХМ-11, ГОСТ / 20 л',
    wb_name: 'Антисептик невымываемый ХМ-11, ГОСТ / 20 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 108,
    id: 319,
    article: '064-65И',
    ean_13: null,
    name: 'ОГНЕБИОЗАЩИТА 2 группа, красный готовый состав / 65 кг',
    cost: 3020,
    recommended_price: 5756,
    category_id: 38,
    ozon_name: '',
    name_1c: 'ОГНЕБИОЗАЩИТА 2 группа, красный готовый состав / 65 кг',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 109,
    id: 449,
    article: '0024-06 м12',
    ean_13: null,
    name: 'Герметик акриловый цвет Медовый 0,6 л (12 шт)',
    cost: null,
    recommended_price: null,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет Медовый 0,6 л (12 шт)',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 110,
    id: 454,
    article: '0024-06 о12',
    ean_13: null,
    name: 'Герметик акриловый цвет Орех, ф/п 600мл (12 штук )',
    cost: null,
    recommended_price: null,
    category_id: 25,
    ozon_name: '',
    name_1c: 'Герметик акриловый цвет сосна, ф/п 600мл (12 штук )',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 111,
    id: 347,
    article: '038-2',
    ean_13: 4680008146151,
    name: 'Антисептик лессирующий BiO LASUR / махагон / 2,7 л',
    cost: 721,
    recommended_price: 1717,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / махагон / 2,7 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / махагон / 2,7 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / махагон / 2,7 л',
    ozon_article: 577611781,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 112,
    id: 283,
    article: '015-65',
    ean_13: 4680008143884,
    name: 'Антисептик  ECO UNIVERSAL / 65 л',
    cost: 2780,
    recommended_price: 6625,
    category_id: 20,
    ozon_name:
      'Антисептик универсальный для наружных и внутренних работPROSEPT ECO UNIVERSALготовый состав / 65 л',
    name_1c: 'Антисептик  ECO UNIVERSAL / 65 л',
    wb_name:
      'Антисептик универсальный для наружных и внутренних работPROSEPT ECO UNIVERSALготовый состав / 65 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 113,
    id: 190,
    article: 'D1 01005',
    ean_13: 4680008148575,
    name: 'Кожный антисептик ПРОФ ДЗ "PROF DZ" готовый состав / 5 л ',
    cost: 1164,
    recommended_price: 0,
    category_id: 21,
    ozon_name: 'Кожный антисептик PROSEPT PROF DZ, 5 л.',
    name_1c: 'Кожный антисептик PROSEPT PROF DZ, 5 л.',
    wb_name: 'Кожный антисептик PROSEPT PROF DZ, 5 л.',
    ozon_article: null,
    wb_article: 150119535,
    ym_article: 'D1-01005',
    wb_article_td: ''
  },
  {
    FIELD1: 114,
    id: 191,
    article: 'D1 02500',
    ean_13: 4610093420041,
    name: 'Дезинфицирующее средство ПРОФ ДЗ "PROF DZ" готовый состав / 0,5 л ',
    cost: 156,
    recommended_price: 0,
    category_id: 21,
    ozon_name: 'Дезинфицирующее средство PROSEPT PROF DZ, 500 мл.',
    name_1c: 'Дезинфицирующее средство PROSEPT PROF DZ, 500 мл.',
    wb_name: 'Дезинфицирующее средство PROSEPT PROF DZ, 500 мл.',
    ozon_article: null,
    wb_article: 150119532,
    ym_article: 'D1-02500',
    wb_article_td: ''
  },
  {
    FIELD1: 115,
    id: 456,
    article: 'М007-2',
    ean_13: 4610093421208,
    name: 'Антисептик для рук PROSEPT PROF DZ, 2 штуки*100 мл.',
    cost: 112,
    recommended_price: 224,
    category_id: 21,
    ozon_name: 'Антисептик для рук PROSEPT PROF DZ, 2 штуки*100 мл.',
    name_1c: '',
    wb_name: '',
    ozon_article: null,
    wb_article: null,
    ym_article: 'D1-01100-2',
    wb_article_td: ''
  },
  {
    FIELD1: 116,
    id: 79,
    article: '265-5',
    ean_13: 4680008146458,
    name: 'Моющее средство для пароконвектоматов с режимом автоматической очисткиCooky Degreaserконцентрат / 5 л',
    cost: 834,
    recommended_price: 1949,
    category_id: 40,
    ozon_name:
      'Моющее средство для пароконвектоматов с режимом автоматической очисткиCooky Degreaserконцентрат / 5 л',
    name_1c:
      'Моющее средство для пароконвектоматов с режимом автоматической очисткиCooky Degreaserконцентрат / 5 л',
    wb_name:
      'Моющее средство для пароконвектоматов с режимом автоматической очисткиCooky Degreaserконцентрат / 5 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 117,
    id: 171,
    article: '145-5/5',
    ean_13: 4680008144201,
    name: 'Жидкое гель-мыло с перламутром. Без цвета, без запахаDiona готовый состав / 5 л ПЭТ',
    cost: 221,
    recommended_price: 479,
    category_id: 33,
    ozon_name:
      'Жидкое гель-мыло с перламутром. Без цвета, без запахаDiona готовый состав / 5 л ПЭТ',
    name_1c: 'Жидкое гель-мыло с перламутром. Без цвета, без запахаDiona готовый состав / 5 л ПЭТ',
    wb_name: 'Жидкое гель-мыло с перламутром. Без цвета, без запахаDiona готовый состав / 5 л ПЭТ',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 118,
    id: 357,
    article: '033-9',
    ean_13: 4680008145925,
    name: 'Антисептик лессирующий BiO LASUR / сосна / 9 л',
    cost: 2159,
    recommended_price: 5145,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / сосна / 9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / сосна / 9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / сосна / 9 л',
    ozon_article: 577437008,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 119,
    id: 423,
    article: '070-12',
    ean_13: 4680008149725,
    name: 'Краска резиновая черный Ral 9004 / 12 кг',
    cost: 3206,
    recommended_price: 6711,
    category_id: 30,
    ozon_name: 'Краска резиновая PROSEPT SuperRubberчерный Ral 9004 / 12 кг',
    name_1c: 'Краска резиновая черный Ral 9004 / 12 кг',
    wb_name: 'Краска резиновая PROSEPT SuperRubberчерный Ral 9004 / 12 кг',
    ozon_article: 575099282,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 120,
    id: 350,
    article: '037-2',
    ean_13: 4680008146038,
    name: 'Антисептик лессирующий BiO LASUR / орех / 2,7 л',
    cost: 721,
    recommended_price: 1717,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / орех / 2,7 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / орех / 2,7 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / орех / 2,7 л',
    ozon_article: 577517844,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 121,
    id: 344,
    article: '034-2',
    ean_13: 4680008146007,
    name: 'Антисептик лессирующий BiO LASUR / лиственница / 2,7 л',
    cost: 721,
    recommended_price: 1717,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / лиственница / 2,7 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / лиственница / 2,7 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / лиственница / 2,7 л',
    ozon_article: 577616286,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 122,
    id: 336,
    article: '031-9',
    ean_13: 4680008145895,
    name: 'Антисептик лессирующий BiO LASUR / бесцветный / 9 л',
    cost: 2159,
    recommended_price: 5145,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / бесцветный / 9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / бесцветный / 9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / бесцветный / 9 л',
    ozon_article: 577628070,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 123,
    id: 333,
    article: '032-9',
    ean_13: 4680008145956,
    name: 'Антисептик лессирующий BiO LASUR / белый люкс / 9 л',
    cost: 2159,
    recommended_price: 5145,
    category_id: 31,
    ozon_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / белый люкс / 9 л',
    name_1c: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / белый люкс / 9 л',
    wb_name: 'Антисептик лессирующийзащитно-декоративныйPROSEPT BiO LASUR / белый люкс / 9 л',
    ozon_article: 577422226,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 124,
    id: 244,
    article: '001-30',
    ean_13: 4680008140586,
    name: 'Отбеливатель для древесиныPROSEPT 50концентрат 1:1 / 30 л',
    cost: 3792,
    recommended_price: 7358,
    category_id: 35,
    ozon_name: 'Отбеливатель для древесины PROSEPT 50концентрат 1:1 / 30 л',
    name_1c: 'Отбеливатель для древесиныPROSEPT 50концентрат 1:1 / 30 л',
    wb_name: 'Отбеливатель для древесиныPROSEPT 50концентрат 1:1 / 30 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 125,
    id: 309,
    article: '007-30',
    ean_13: 4680008140555,
    name: 'Огнебиозащита ОГНЕБИО PROF l, 1 группа, красный готовый состав / 30 л',
    cost: 2267,
    recommended_price: 5401,
    category_id: 38,
    ozon_name:
      'Огнебиозащита для древесиныPROSEPT ОГНЕБИО PROF l,1 группа, красный готовый состав / 30 л',
    name_1c:
      'Огнебиозащита для древесиныPROSEPT ОГНЕБИО PROF l,1 группа, красный готовый состав / 30 л',
    wb_name:
      'Огнебиозащита для древесиныPROSEPT ОГНЕБИО PROF l,1 группа, красный готовый состав / 30 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 126,
    id: 305,
    article: '007-65бц',
    ean_13: 4680008146199,
    name: 'Огнебиозащита   ОГНЕБИО PROF l, 1 группа, бесцветный готовый состав / 65 л',
    cost: 4838,
    recommended_price: 11529,
    category_id: 38,
    ozon_name:
      'Огнебиозащита для древесины PROSEPT ОГНЕБИО PROF l,1 группа, бесцветный готовый состав / 65 л',
    name_1c:
      'Огнебиозащита для древесины PROSEPT ОГНЕБИО PROF l,1 группа, бесцветный готовый состав / 65 л',
    wb_name:
      'Огнебиозащита для древесины PROSEPT ОГНЕБИО PROF l,1 группа, бесцветный готовый состав / 65 л',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 127,
    id: 301,
    article: '007-5бц',
    ean_13: 4680008145000,
    name: 'Огнебиозащита ОГНЕБИО PROF I, 1 группа, бесцветный готовый состав / 5 л',
    cost: 407,
    recommended_price: 970,
    category_id: 38,
    ozon_name:
      'Огнебиозащита для древесиныPROSEPT ОГНЕБИО PROF I1 группа, бесцветный готовый состав / 5 л',
    name_1c:
      'Огнебиозащита для древесиныPROSEPT ОГНЕБИО PROF I1 группа, бесцветный готовый состав / 5 л',
    wb_name:
      'Огнебиозащита для древесиныPROSEPT ОГНЕБИО PROF I1 группа, бесцветный готовый состав / 5 л',
    ozon_article: 508035205,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  },
  {
    FIELD1: 128,
    id: 499,
    article: 'М037-2',
    ean_13: 4610093421413,
    name: 'Антисептик ULTRA коричневый, концентрат, 1 л, 2 шт',
    cost: 720,
    recommended_price: 1645,
    category_id: null,
    ozon_name: 'Антисептик ULTRA коричневый, концентрат, 1 л, 2 шт',
    name_1c: 'Антисептик ULTRA коричневый, концентрат, 1 л, 2 шт',
    wb_name: 'Антисептик ULTRA коричневый, концентрат, 1 л, 2 шт',
    ozon_article: null,
    wb_article: null,
    ym_article: '',
    wb_article_td: ''
  }
];
